#!/bin/bash
# Deploy Shopify Theme Extension

echo "🚀 Deploying Theme Extension to Shopify..."
echo ""
echo "Since Shopify CLI is not available, follow these manual steps:"
echo ""
echo "📋 MANUAL DEPLOYMENT STEPS:"
echo ""
echo "1. Go to Shopify Partner Dashboard:"
echo "   https://partners.shopify.com/organizations"
echo ""
echo "2. Navigate to:"
echo "   Apps → ihear.ai (or your app name) → Extensions"
echo ""
echo "3. Find the extension:"
echo "   'AI Sales Assistant' (Theme Extension)"
echo ""
echo "4. Click 'Create version' or 'Deploy' button"
echo ""
echo "5. Review changes and click 'Deploy'"
echo ""
echo "6. Wait 1-2 minutes for deployment"
echo ""
echo "7. Refresh your store page"
echo ""
echo "✅ After deployment:"
echo "   - Hard refresh your store (Ctrl+Shift+R)"
echo "   - Check if safeInit function exists"
echo "   - Widget should appear automatically"
echo ""
echo "📝 Files that were updated in extension:"
echo "   - blocks/ai_sales_assistant.liquid (added default values)"
echo "   - assets/ai-sales-assistant.js (fixed API endpoint)"
echo ""
